# Site Settings
name: shamvoke
title: shamvoke blog | ALL CURSORS HAVE A POINT
description: A tech blog by Sham (Voke) — Creative Design, Web Dev, Graphic Design, Thoughts, Stories and Ideas.
tags:
  - shamvoke
  - tech
  - blog
  - Linux
  - youtube
  - web development
  - programming
show_hero: true
menu:
  - title: Home
    url: /
  - title: Blog
    url: /category/blog
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: shamvoke@webmeka.com
# Commentbox id
commentbox_project_id: 5704915259228160-proj
# Contact Form Setting
formspree_form_id: xkgzlbqz


# Social Media Settings
# Remove the item if you don't need it
github_username: shamvoke
facebook_username: share/17911CWaJV/
twitter_username: webmeka
instagram_username: webmeka
youtube_username: shamvoke

# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: true


# Advanced Settings
baseurl: ""
url: "https://shamvoke.com" 
google_analytics: "G-EBDRYQY434"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_youtube_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'docs/',
  'vendor/',
  'LICENSE',
  'CHANGELOG.md',
  'jekflix.gemspec',
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

timezone: Africa/Nairobi
# Theme
version: Blog loading...
