services:
  blog:
    container_name: shamvoke-blog
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3001:3001"
    command: >
      sh -c "
        npm install &&
        bundle install &&
        bundle exec jekyll build &&
        gulp
      "