name: shamvoke
title: shamvoke blog | ALL CURSORS HAVE A POINT
description: A tech blog by Sham (Voke) — Creative Design, Web Dev, Graphic Design, Thoughts, Stories and Ideas.
tags:
  - shamvoke
  - tech
  - blog
  - Linux
  - youtube
  - web development
  - programming
show_hero: true
menu:
  - title: Home
    url: /
  - title: Blog
    url: /category/blog
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: shamvoke@webmeka.com
# Commentbox id
commentbox_project_id: 5704915259228160-proj
# Contact Form Setting
formspree_form_id: xkgzlbqz
