name: shamvoke
title: shamvoke | The official blog of shamvoke
description: A tech blog by Sham (Voke) — creative design, web dev, graphic design, ideas and reflections.
tags:
  - shamvoke
  - tech
  - blog
  - Linux
  - jekyll
  - youtube
  - technology
  - netlify
  - web development
  - programming
show_hero: true
menu:
  - title: Home
    url: /
  - title: Blog
    url: /category/blog
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: shamvoke@webmeka.com
# Commentbox id
commentbox_project_id: 5764025115738112-proj
# Contact Form Setting
formspree_form_id: xkgzlbqz
