#local_backend: true

backend:
  name: github
  repo: shamvoke/shamvoke
  branch: master
  base_url: https://shamvoke.com
  auth_endpoint: /api/auth

site_url: https://shamvoke.com
display_url: https://shamvoke.com
logo_url: https://shamvoke.com/favicon.ico

media_folder: "public/_FeaturedImages"
public_folder: "/_FeaturedImages"

publish_mode: simple

collections:
  - name: "posts"
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "src/_posts"
    create: true
    delete: true
    extension: "md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}}"
    editor:
      preview: false

    fields:
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ss[Z]"
        date_format: "YYYY-MM-DD"
        time_format: "HH:mm:ss"
        default: "{{now}}"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Shamthing"
        name: "shamthing"
        widget: "string"
        required: false

      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
        required: false

      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
        required: false

      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - "software"
          - "linux"
          - "life"
          - "code"
          - "design"
          - "windows"

      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field:
          label: "Tag"
          name: "tag"
          widget: "string"

      - label: "Body"
        name: "body"
        widget: "markdown"